# Generated by Django 2.1.5 on 2019-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190205_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
