# Generated by Django 2.1.5 on 2019-02-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
