# Generated by Django 2.1.5 on 2019-02-06 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participate',
            field=models.ManyToManyField(blank=True, related_name='participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
